### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by joncfoo** [rstudio/rsconnect-jupyter#157]
We've made a few important changes and it feels like we should release this to a publicly available channel. We should publish this to PyPi

**Comment by scottmmjackson** [comment]
Just for the sake of capturing resources about this: https://wiki.python.org/moin/CheeseShopTutorial

**Comment by mmarchetti** [comment]
* [x] build both sdist and bdist_wheel (we current build only the wheel) - Makefile update
* [x] Register an account on test.pypi.org
* [x] install `twine` and upload to the test server (`python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*.{gz,whl}`) - be careful since local builds and docs also end up in the dist/ folder, also make sure to build with the correct version and `BUILD_NUMBER` - in Jenkinsfile
* [x] verify package and file info on test.pypi.org
* [x] install from test.pypi.org (`python3 -m pip install --index-url https://test.pypi.org/simple/ rsconnect_jupyter`) and smoke test - done via new makefile targets e.g. `pypi-test-run3.6`
* [x] create an account on pypi.org
* [ ] upload there (`twine upload dist/*.{gz,whl}`)
* [ ] verify package and file info
* [ ] install (`pip install rsconnect_jupyter`) and smoke test
* [x] create an rstudio account at PyPI and make it a maintainer of the package
* [x] create a CI pipeline similar to the docs pipeline, and put the org account credentials in it

**Comment by mmarchetti** [comment]
Testing notes:
* install (`pip install rsconnect_jupyter`) and test
* Review project information and docs on PyPI (note images are missing)

**Comment by kgartland-rstudio** [comment]
Verified
