### ISSUE TITLE
Investigate what is required to publish to PyPi

### ISSUE THREAD

**Issue by joncfoo** [rstudio/rsconnect-jupyter#158]
Compile a list of steps that we need to do in order to publish to PyPi

**Comment by mmarchetti** [comment]
Preliminary look: https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

For our first time through:
* build both sdist and bdist_wheel (we current build only the wheel) - Makefile update
* Register an account on test.pypi.org 
* install `twine` and upload to the test server (`python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*.{gz,whl}`) - be careful since local builds and docs also end up in the dist/ folder, also make sure to build with the correct version and `BUILD_NUMBER`
* verify package and file info on test.pypi.org
* install from test.pypi.org (`python3 -m pip install --index-url https://test.pypi.org/simple/ rsconnect_jupyter`) and smoke test
* create an account on pypi.org
* upload there (`twine upload dist/*.{gz,whl}`)
* verify package and file info
* install (`pip install rsconnect_jupyter`) and smoke test

**Comment by mmarchetti** [comment]
We also need to put a proper user readme into README.md since that is displayed on pypi (see https://test.pypi.org/project/rsconnect-jupyter/ if it hasn't been purged yet)

**Comment by mmarchetti** [comment]
We also need to:
* put a proper user readme into README.md since that is displayed on pypi (see https://test.pypi.org/project/rsconnect-jupyter/ if it hasn't been purged yet)
* create an rstudio account at PyPI and make it a maintainer of the package
* create a CI pipeline similar to the docs pipeline, and put the org account credentials in it

**Comment by slopp** [comment]
@kgartland-rstudio  Was this closed because the package is now on PyPi? Or for some other reason?

**Comment by kgartland-rstudio** [comment]
This was just a spike.  Mike was investigating what was required to get this on PyPi.
